// svelte-4/src/components/Header/Header.svelte
<script>
	import NavLinks from '../NavLinks/NavLinks.svelte';
	import Logo from '../Logo/Logo.svelte';
</script>

<header class="flex justify-center">
	<nav class="flex flex-1 h-20 items-center px-4 w-full max-w-screen-xl">
		<Logo />
		<NavLinks />
		<section>
			<a href="/">Log In</a>
		</section>
	</nav>
</header>

// next-14/components/Header/Header.tsx
import Logo from "../Logo"
import NavLinks from "../NavLinks"
import UserAccount from "../UserAccount"

const Header = () => {
  return (
    <>
      <header className="flex justify-center">
        <nav className="flex flex-1 h-20 items-center px-4 w-full max-w-screen-xl">
          <Logo />
          <NavLinks />
          <UserAccount />
        </nav>
      </header>
    </>
  )
}

export default Header
